const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.Car,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Keyboard,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Behaviors.Car.Exps.Speed,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Behaviors.Car.Acts.SetMaxSpeed,
		C3.Behaviors.Car.Acts.SetSteerSpeed,
		C3.Behaviors.Car.Acts.SetDriftRecover,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Shape3D.Cnds.IsBetweenAngles,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Shape3D.Acts.SetTowardPosition
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Car: 0},
	{Sine: 0},
	{Solid: 0},
	{Fence: 0},
	{FenceTexture: 0},
	{ConeTip: 0},
	{Tween: 0},
	{ConeBase: 0},
	{CarFrontWindow: 0},
	{wheelPosition: 0},
	{CarWheel: 0},
	{CarShadow: 0},
	{CarMiddleWindows: 0},
	{CarBackWindow: 0},
	{CarExhaust: 0},
	{Ground: 0},
	{FailZone: 0},
	{CarBumper: 0},
	{CarFrontWindowSmall: 0},
	{ID: 0},
	{Objective: 0},
	{Rotate: 0},
	{ObjectiveArrow: 0},
	{Grass: 0},
	{Building0: 0},
	{Building1: 0},
	{Building2: 0},
	{TextTutorial: 0},
	{Keyboard: 0},
	{TextCountdown: 0},
	{TextFail: 0},
	{Tree0: 0},
	{Tree1: 0},
	{Fader: 0},
	{TextTimer: 0},
	{Timer: 0},
	{ParallelParkingZone: 0},
	{ObjectiveArrowTexture: 0},
	{Flash: 0},
	{TextInfo: 0},
	{CarBrakeLights: 0},
	{CarWheelRightTexture: 0},
	{CarWheelLeftTexture: 0},
	{SmokeTexture: 0},
	{Smoke: 0},
	{ConeBaseFamily: 0},
	{CarFamily: 0},
	{Trees: 0},
	{CAMERA_CHASE_SPEED: 0},
	{CAMERA_CHASE_DISTANCE: 0},
	{CAR_FORWARD_MAX_SPEED: 0},
	{CAR_REVERSE_MAX_SPEED: 0},
	{CAR_STEER_SPEED: 0},
	{CAR_DRIFT_RECOVER: 0},
	{objCounter: 0},
	{tutorial: 0},
	{levelFinished: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	Car: class extends self.I3DShapeInstance {},
	Fence: class extends self.I3DShapeInstance {},
	FenceTexture: class extends self.ITiledBackgroundInstance {},
	ConeTip: class extends self.I3DShapeInstance {},
	ConeBase: class extends self.I3DShapeInstance {},
	CarFrontWindow: class extends self.I3DShapeInstance {},
	CarWheel: class extends self.I3DShapeInstance {},
	CarShadow: class extends self.ITiledBackgroundInstance {},
	CarMiddleWindows: class extends self.I3DShapeInstance {},
	CarBackWindow: class extends self.I3DShapeInstance {},
	CarExhaust: class extends self.I3DShapeInstance {},
	Ground: class extends self.ISpriteInstance {},
	FailZone: class extends self.ISpriteInstance {},
	CarBumper: class extends self.I3DShapeInstance {},
	CarFrontWindowSmall: class extends self.I3DShapeInstance {},
	Objective: class extends self.ISpriteInstance {},
	ObjectiveArrow: class extends self.I3DShapeInstance {},
	Grass: class extends self.ITiledBackgroundInstance {},
	Building0: class extends self.I3DShapeInstance {},
	Building1: class extends self.I3DShapeInstance {},
	Building2: class extends self.I3DShapeInstance {},
	TextTutorial: class extends self.ISpriteFontInstance {},
	Keyboard: class extends self.IInstance {},
	TextCountdown: class extends self.ISpriteFontInstance {},
	TextFail: class extends self.ISpriteFontInstance {},
	Tree0: class extends self.I3DShapeInstance {},
	Tree1: class extends self.I3DShapeInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTimer: class extends self.ISpriteFontInstance {},
	Timer: class extends self.ISpriteInstance {},
	ParallelParkingZone: class extends self.ISpriteInstance {},
	ObjectiveArrowTexture: class extends self.ISpriteInstance {},
	TextInfo: class extends self.ISpriteFontInstance {},
	CarBrakeLights: class extends self.ISpriteInstance {},
	CarWheelRightTexture: class extends self.ISpriteInstance {},
	CarWheelLeftTexture: class extends self.ISpriteInstance {},
	SmokeTexture: class extends self.ISpriteInstance {},
	Smoke: class extends self.I3DShapeInstance {},
	ConeBaseFamily: class extends self.I3DShapeInstance {},
	CarFamily: class extends self.I3DShapeInstance {},
	Trees: class extends self.I3DShapeInstance {}
}